CREATE TABLE IF NOT EXISTS api_keys (
    id INTEGER PRIMARY KEY DEFAULT nextval('api_keys_id_seq'),
    key VARCHAR UNIQUE NOT NULL,
    name VARCHAR NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP