ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN SchoolDist TO school_dist;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN PolicePrct TO police_prct;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN LandUse TO land_use;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN OwnerType TO owner_type;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN OwnerName TO owner_name;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN LotArea TO lot_area;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN BldgArea TO bldg_area;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN ComArea TO com_area;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN ResArea TO res_area;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN LotDepth TO lot_depth;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN OfficeArea TO office_area;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN RetailArea TO retail_area;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN GarageArea TO garage_area;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN StrgeArea TO strge_area;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN FactryArea TO factry_area;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN OtherArea TO other_area;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN AreaSource TO area_source;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN NumBldgs TO num_bldgs;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN NumFloors TO num_floors;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN UnitsRes TO units_res;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN UnitsTotal TO units_total;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN LotFront TO lot_front;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN BldgFront TO bldg_front;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN BldgDepth TO bldg_depth;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN Ext TO ext;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN LotType TO lot_type;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN BsmtCode TO bsmt_code;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN AssessLand TO assess_land;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN AssessTot TO assess_tot;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN ExemptTot TO exempt_tot;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN YearBuilt TO year_built;
ALTER TABLE nycdb.main.pluto_latest RENAME COLUMN BBL TO bbl;

ALTER TABLE nycdb.main.pluto_latest DROP COLUMN cd;
ALTER TABLE nycdb.main.pluto_latest DROP COLUMN ct2010;
ALTER TABLE nycdb.main.pluto_latest DROP COLUMN latitude;
ALTER TABLE nycdb.main.pluto_latest DROP COLUMN longitude;
ALTER TABLE nycdb.main.pluto_latest DROP COLUMN landusedesc;
ALTER TABLE nycdb.main.pluto_latest DROP COLUMN latitudelongitudegeom;